name: "FFmpeg Android Builder"
description: "Build FFmpeg for Android"
author: "Ishan09811 & Javernaut(creator of the actual script)"

branding:
  icon: "package"
  color: "purple"
  
inputs:
  sdk-path:
    description: "Android SDK path"
    required: false
    default: "$ANDROID_HOME"

  ndk-path:
    description: "Android NDK path"
    required: false
    default: "$ANDROID_NDK_HOME"
    
  android-api:
    description: "Android API level"
    required: false
    default: "34"

  abis:
    description: "list of ABIs"
    required: false
    default: "arm64-v8a"

  output-dir:
    description: "Directory where FFmpeg will output its build result"
    required: false
    default: "./output"

  extra-args:
    description: "Additional flags passed to FFmpeg"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build FFmpeg
      shell: bash
      run: |
        chmod +x ./ffmpeg-android-maker.sh
        export ANDROID_SDK_HOME=${{ inputs.sdk-path }}
        export ANDROID_NDK_HOME=${{ inputs.ndk-path }}
        ./ffmpeg-android-maker.sh \
          -android=${{ inputs.android-api }} \
          -abis=${{ inputs.abis }} \
          ${{ inputs.extra-args }}

        if [ "${{ inputs.output-dir }}" != "./output" ]; then
          mv ./output "${{ inputs.output-dir }}"
        fi

outputs:
  output-path:
    description: "Path where built libraries and include files are stored"
    value: ${{ inputs.output-dir }}
